name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every Monday at 1:00 AM
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Adding actions/checkout assuming you need to checkout the repository
      - name: Set up Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCtUA3gHBQwxn5C2L5xMRF0Q
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          max_videos: 3
