name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every Monday at 1:00 AM
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: actions/checkout@v4
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCtUA3gHBQwxn5C2L5xMRF0Q
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
          max_videos: 3
